import 'package:get/get.dart';

class Strings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'app_name': 'Awign',
          'server_error':
              'We regret the technical error. Please try again after some time.',
          'welcome_text': 'Welcome to Awign',
          'login_using_email': 'Login using email',
          'by_continuing': 'By continuing, you agree to our',
          'privacy_policy': 'Privacy policy',
          'and': 'and',
          'terms_and_conditions': 'Terms & Conditions',
          'email': 'Email',
          'enter_email': 'Enter Email',
          'enter_valid_email': 'Please enter a valid email address',
          'enter_registered_email_address':
              'Please enter registered email address.',
          'password': 'Password',
          'enter_valid_password': 'Please enter valid password',
          'password_must_be': 'Password must be at least 6 characters long',
          'sign_in': 'Sign In',
          'forgot_password': 'Forgot Password?',
          'personal_details': 'Personal Details',
          'name': 'Name',
          'enter_name': 'Enter Name',
          'enter_valid_name': 'Please enter valid name',
          'name_should_contain': 'Name should contain only alphabets and space',
          'gender': 'Gender',
          'please_select_gender': 'Please select gender',
          'male': 'Male',
          'female': 'Female',
          'other': 'Other',
          'date_of_birth': 'Date of birth',
          'please_enter_dob': 'Please enter your date of birth',
          'please_select_dob': 'Please select your date of birth',
          'dd': 'DD',
          'mm': 'MM',
          'yyyy': 'YYYY',
          'what_all_languages': 'What all languages do you speak?',
          'select_language': 'Select Languages',
          'please_select_language': 'Please select language',
          'hindi': 'Hindi',
          'english': 'English',
          'bengali': 'Bengali',
          'marathi': 'Marathi',
          'tamil': 'Tamil',
          'gujarati': 'Gujarati',
          'urdu': 'Urdu',
          'telugu': 'Telugu',
          'kannada': 'Kannada',
          'odia': 'Odia',
          'malayalam': 'Malayalm',
          'panjabi': 'Panjabi',
          'assamese': 'Assamese',
          'maithili': 'Maithili',
          'sanskrit': 'Sanskrit',
          'submit': 'Submit',
          'user_location': 'Your Location',
          'use_my_current_location': 'Use my current location',
          'or': 'Or',
          'address': 'Address',
          'search_by_area': 'Search by area, street, locality',
          'select_valid_address': 'Select valid address',
          'pincode': 'Pincode',
          'enter_valid_pincode': 'Enter valid pincode',
          'next': 'Next',
          'selected_location': 'Selected Location',
          'confirm': 'Confirm',
          'search_locality': 'Search a locality, e.g. Indira nagar',
          'enter_mobile_number': 'Enter Mobile Number',
          'mobile_number': 'Mobile Number',
          'receive_message_on': 'Receive Updates on WhatApp',
          'whatsapp': ' WhatsApp',
          '91': '+91',
          'education_details': 'Education Details',
          'education_level': 'Education Level',
          'select_education_level': 'Select Education Level',
          'have_you_worked_before': 'Have you worked before?',
          'yes': 'Yes',
          'no': 'No',
          'select_your_working_domain': 'Select your working domain',
          'below_10th': 'Below 10th',
          '10th_pass': '10th Pass',
          '12th_pass': '12th Pass',
          'pursuing_graduation': 'Pursuing Graduation',
          'graduate': 'Graduate',
          'post_graduate': 'Post Graduate',
          'calling': 'Calling',
          'data_entry': 'Data Entry',
          'field_job': 'Field Job',
          'delivery_job': 'Delivery Job',
          'sales': 'Sales',
          'marketing': 'Marketing',
          'business_development': 'Business Development',
          'others': 'Others',
          'otp_verification': 'OTP Verification',
          'enter_your_otp': 'Enter your OTP',
          'otp_resend_in': 'OTP Resend in',
          'we_regret_the_technical_error':
              'We regret the technical error. Please try again after some time.',
          'loading': 'Loading...',
          'help': 'Help',
          'logout': 'Logout',
          'continue_with_google': 'Continue with google',
          'continue': 'Continue',
          'please_wait': 'Please wait...',
          'verifying': 'Verifying...',
          'enter_valid_mobile_number':
              'Please enter a valid 10 digit mobile number',
          'enter_registered_mobile_number':
              'Please enter registered mobile number.',
          'enter_valid_otp': 'Please enter valid otp',
          'resend_otp': 'Resend OTP',
          'please_select_your_domain': 'Please Select Your Domain',
          'please_select_education_level': 'Please Select Education Level',
          'office': 'Office',
          'category_listing': 'Jobs',
          'earnings': 'Earnings',
          'more': 'More',
          'edit': 'Edit',
          'become_campus_ambassador': 'Campus Ambassador',
          'share_app': 'Share App',
          'application_history': 'Application History',
          'faq_and_support': 'FAQs & Support',
          'id_proof': 'ID Proof',
          'unsubscribe_from_calls': 'Unsubscribe from calls, Text & Mail',
          'language': 'Language',
          'dark_mode': 'Dark Mode',
          'edit_profile': 'Edit Profile',
          'phone': 'Phone',
          'change': 'Change',
          'add_new': '+ Add new',
          'college_details': 'College Details',
          'collage_name': 'Collage name',
          'field_of_study': 'Field of study',
          'select_degree': 'Select degree',
          'start_year': 'Start year',
          'end_year': 'End year',
          'education_and_professional_details':
              'Education & Professional Details',
          'qualification': 'Qualification',
          'select_qualification': 'Select Qualification',
          'professional_domain': 'Profession Domain',
          'select_domain': 'Select Domain',
          'other_details': 'Other Details',
          'do_you_have_android': 'Do you have an Android phone? ()',
          'engineering': 'Engineering',
          'management_and_business_administration':
              'Management & Business Administration',
          'arts': 'Arts',
          'science': 'Science',
          'commerce': 'Commerce',
          'humanities': 'Humanities',
          'social_science': 'Social Science',
          'information_technology': 'Information Technology',
          'computer_applications': 'Computer Applications',
          'architecture': 'Architecture',
          'fashion_and_design': 'Fashion and Design',
          'mass_communication': 'Mass Communication',
          'media': 'Media',
          'journalism': 'Journalism',
          'design': 'Design',
          'animation': 'Animation',
          'hotel_management': 'Hotel Management',
          'hospitality': 'Hospitality',
          'travel_and_tourism': 'Travel &amp; Tourism',
          'teaching_or_educational': 'Teaching/Educational',
          'performing_arts': 'Performing Arts',
          'banking': 'Banking',
          'agriculture': 'Agriculture',
          'aviation': 'Aviation',
          'law': 'Law',
          'medical': 'Medical',
          'dental': 'Dental',
          'pharmacy': 'Pharmacy',
          'nursing': 'Nursing',
          'paramedical': 'Paramedical',
          'veterinary_sciences': 'Veterinary Sciences',
          'dance': 'Dance',
          'music': 'Music',
          'acting_or_drama': 'Acting/Drama',
          'sports': 'Sports',
          'distance_education': 'Distance Education',
          'polytechnic_or_diploma': 'Polytechnic/Diploma',
          'iti': 'I.T.I',
          'vocational_training': 'Vocational training',
          'other_stream': 'Other stream',
          'choose_start_year': 'Choose Start Year',
          'set': 'SET',
          'choose_end_year': 'Choose End Year',
          'referral': 'Referral',
          'my_profile': 'My Profile',
          'notification_history': 'Notification History',
          'help_and_support': 'Help & Support',
          'kyc_details': 'KYC Details',
          'personal_info': 'Personal Info',
          'mobile_no': 'Mobile No.',
          'email_id': 'Email ID',
          'dob': 'DOB',
          'whatsapp_updates': 'WhatsApp Updates',
          'inactive': 'Inactive',
          'active': 'Active',
          'collage': 'Collage',
          'degree': 'Degree',
          'field': 'Field',
          'year': 'Year',
          'professional_details': 'Professional Details',
          'edit_personal_info': 'Edit Personal Info',
          'save_changes': 'Save Changes',
          'get_otp': 'Get OTP',
          'edit_address': 'Edit Address',
          'area': 'Area',
          'city': 'City',
          'state': 'State',
          'enter_valid_area': 'Please enter valid area',
          'enter_valid_city': 'Please enter valid city',
          'enter_valid_state': 'Please enter valid state',
          'search': 'Search',
          'enter_valid_collage_name': 'Please enter valid collage name',
          'select_field_of_study': 'Please select field of study',
          'enter_valid_other_stream': 'Please enter valid other stream',
          'select_valid_start_year': 'Please select valid start year',
          'select_valid_end_year': 'Please select valid end year',
          'please_select_valid_start_year_end_year':
              'Please select valid start year and end year',
          'invalid_value': 'Invalid value',
          'edit_other_details': 'Edit Other Details',
          'edit_professional_details': 'Edit Professional Details',
          'explore': 'Explore',
          'job_categories': 'Job Categories',
          'explore_jobs_by_categories': 'Explore jobs by categories',
          'share': 'Share',
          'view': 'View',
          'jobs': 'Jobs',
          'in_order_to_view_available_jobs':
              'In order to view available jobs please answer a few simple question about yourself.',
          'fill_application_form': 'Fill Application Form',
          'who_can_apply': 'Who can apply?',
          'description': 'Description',
          'roles_and_responsibilities': 'Roles & Responsibilities',
          'what_you_get': 'What you get?',
          'job': 'Job',
          'my_jobs': 'My Jobs',
          'pending_jobs': 'Pending Jobs',
          'view_jobs': 'View Jobs',
          'application_form': 'Application Form',
          'incorrect_answer': 'Incorrect Answer',
          'select_from_options': 'Select from options',
          'not_answered': 'Not answered',
          'enter_here': 'Enter Here',
          'required_questions': 'required questions',
          'please_answer': 'Please answer',
          'go_to_office': 'Go to office',
          'explore_job': 'Explore Jobs',
          'reapply': 'Re-Apply',
          'enter_valid_number': 'Please enter valid number',
          'enter_valid_pan_number': 'Please enter valid PAN number',
          'enter_valid_dl_number': 'Please enter valid DL number',
          'enter_valid_float_number': 'Please enter valid float number',
          'enter_valid_url': 'Please enter valid URL',
          'incorrect_value': 'Incorrect value',
          'select_time': 'Select Time',
          'cancel': 'Cancel',
          'set_time': 'Set Time',
          'from': 'From',
          'to': 'To',
          'start_time': 'Start Time',
          'end_time': 'End Time',
          'start_date': 'Start Date',
          'end_date': 'End Date',
          'start_date_time_is_empty':
              'Start Date/Time should be selected first',
          'invalid_end_date': 'End Date cannot be lesser than Date time',
          'invalid_end_time': 'End time cannot be lesser than start time',
          'invalid_end_date_time':
              'End DateTime cannot be lesser than start DateTime',
          'select_file': 'Select File',
          'select_image': 'Select Image',
          'select_audio': 'Select Audio',
          'select_video': 'Select Video',
          'select_pdf': 'Select PDF',
          'get_started': 'Get Started!',
          'start_working_on_your_jobs': 'Start working on your jobs',
          'wait_listed': 'Wait Listed',
          'on_hold': 'On Hold',
          'completed': 'Completed',
          'disqualified': 'Disqualified',
          'sign_offer_letter': 'Sign Offer Letter',
          'offer_letter_not_available_please_contact_customer_support':
              'OfferLetter not available please contact customer support',
          'enter_address': 'Enter Address',
          'search_your_city': 'Search your city',
          'search_your_pincode': 'Search your pincode',
          'search_your_state': 'Search your state',
          'signature': 'Signature',
          'tap_to_choose_signature': 'Tap to choose signature',
          'please_select_signature_you_want_to_add':
              'Pleaes select signature you want to add on the offer letter',
          'confirm_and_accept': 'Confirm & Accept',
          'please_select_signature': 'Please select signature',
          'complete_pending_steps_to_start_working_on_below_jobs':
              'Complete pending steps to start working on\nbelow jobs',
          'view_details': 'View Details',
          'all_india': 'All India',
          'no_job_started': 'No job started',
          'are_you_sure_you_want_to_quit': 'Are you sure you want to quit?',
          'yes_i_want_to_quit': 'Yes I want to quit',
          'not_able_to_answer': 'Not able to answer',
          'view_material': 'View material',
          'location': 'Location',
          'duration': 'Duration',
          'work_hours': 'Work Hours',
          'four_to_five_hours_per_day': '4-5 hours per day',
          'seven_to_eight_hours_per_day': '7-8 hours per day',
          'stipend': 'Stipend',
          'requirement': 'Requirement',
          'please_check_who_can_apply': 'Please check who can apply',
          'work_from_home': 'Work from home',
          'confirm_slot': 'Confirm Batch',
          'change_slot': 'Change Batch',
          'select_a_time_slot': 'Select a time slot',
          'today': 'Today',
          'tomorrow': 'Tomorrow',
          'morning': 'Morning',
          'afternoon': 'Afternoon',
          'evening': 'Evening',
          'slot': 'Slot',
          'slots': 'Slots',
          'view_more': 'View more',
          'view_less': 'View less',
          'schedule_slot': 'Schedule Slot',
          'please_select_a_time_slot': 'Please select a time slot',
          'slot_scheduled': 'Slot scheduled',
          'prepare_for_interview': 'Prepare For Interview',
          'reschedule': 'Reschedule',
          'did_your_interview_happen': 'Did your interview happen?',
          'did_your_training_happen': 'Did your training happen?',
          'did_your_pitch_demo_happen': 'Did your pitch demo happen?',
          'select_a_batch': 'Select a batch',
          'confirm_training_batch': 'Confirm Training Batch',
          'please_select_a_batch': 'Please select a batch',
          'batch_scheduled': 'Batch Scheduled',
          'unable_to_join_training': 'Unable to join training?',
          'join_training': 'Join Training',
          'record_your_audio': 'Record your Audio',
          'start_recording': 'Start Recording',
          'stop_recording': 'Stop Recording',
          'save': 'Save',
          'record_again': 'Record Again',
          'retry': 'Retry',
          'dashboard': 'Dashboard',
          'tasks': 'Tasks',
          'offer_letter': 'Offer Letter',
          'application_details': 'Application Details',
          'total_earnings': 'TOTAL EARNINGS',
          'view_breakup': 'View Breakup',
          'project_faqs': 'Project FAQs',
          'request_certificate': 'Request Certificate',
          'download_certificate': 'Download Certificate',
          'requested_certificate': 'Requested Certificate',
          'speed_up_your_application_process':
              'Speed up your application process',
          'complete_profile': 'Complete profile',
          'profile_complete': 'Profile Complete',
          'back': 'Back',
          'home': 'Home',
          'no_task': 'No Task',
          'add_lead': 'Add Lead',
          'sample_lead': 'Sample Lead',
          'update_lead': 'Update Lead',
          'i_want_to': 'I want to',
          'add_new_task_by_yourself': 'Add New task by Yourself',
          'request_task_from_manager': 'Request task from Manager',
          'save_and_exit': 'Save & Exit',
          'you_have_not_applied_for_any_jobs':
              'You have not applied for any jobs',
          'explore_jobs': 'Explore Jobs',
          'click_to_add_answer': 'Click to add answer',
          'add_multiple_values': 'Add Multiple Values',
          'add_more': '+ Add More',
          'answers_filled': 'Answers filled',
          'please_fill_already_input_first': 'Please fill already input first',
          'fields_added': 'field(s) added',
          'are_you_sure': 'Are you sure?',
          'please_select_location': 'Please select location',
          'tap_to_get_location': 'Tap to get location',
          'application_id': 'Application Id',
          'execution_id': 'Execution Id',
          'got_it': 'Got it!',
          'resources': 'Resources',
          'view_image': 'View image',
          'application_id_description':
              'Application ID is created to uniquely identify your application for this job. You could use this if you wish to raise any concern with the awign support to resolve queries faster',
          'execution_id_description':
              'Execution ID is created once you complete your application and can start working for this job. You could use this if you wish to raise any concern with your manager/awign support to resolve queries faster',
          'camera': 'Camera',
          'gallery': 'Gallery',
          'preview': 'Preview',
          'quality': 'Quality',
          'rotate': 'Rotate',
          'retake': 'Retake',
          'delete': 'Delete',
          'confirm_and_upload': 'Confirm And Upload',
          'low_quality': 'Low Quality',
          'high_quality': 'High Quality',
          'low_quality_image_selected': 'Low quality image selected',
          'high_quality_image_selected': 'High quality image selected',
          'delete_image': 'Delete Image',
          'are_you_sure_want_to_delete_this_image':
              'Are you sure want to delete this image. You won\'t be able to see it again.',
          'upload_later': 'Upload Later',
          'choose': 'Choose',
          'take_photo': 'Take photo',
          'pick_from_gallery': 'Pick from gallery',
          'choose_from_gallery': 'Choose From Gallery',
          'frequently_asked_questions': 'Frequently Asked Questions',
          'chat_with_us': 'Chat With Us',
          'need_more_help': 'Need more help?',
          'contact_support': 'Contact Support',
          'email_us': 'Email Us',
          'call_us': 'Call Us',
          'enter_4_digit_pin': 'Enter 4 digit PIN',
          'forgot_pin': 'Forgot PIN',
          'forgot_pin_with_question_mark': 'Forgot PIN?',
          'page_locked': 'Page Locked',
          'enter_valid_pin': 'Enter valid PIN',
          'registered_email_address': 'Registered Email Address',
          'registered_mobile_number': 'Registered Mobile Number',
          'enter_email_address': 'Enter Email Address',
          'enter_date_of_birth': 'Enter date of birth',
          'confirm_pin': 'Confirm PIN',
          'enter_pin': 'Enter PIN',
          'set_pin': 'Set PIN',
          'okay_got_it': 'Okay, got it',
          'withdrawal_history': 'Withdrawal History',
          'earning_statement': 'Earning Statement',
          'manage_beneficiary': 'Manage Beneficiary',
          'failed': 'Failed',
          'processing': 'Processing',
          'your_request_should_be_processed_in_the_next_few_days':
              'Your request should be processed in the next few days',
          'reason': 'Reason',
          'ref_id': 'Ref Id',
          'successful': 'Successful',
          'lifetime_earnings': 'Lifetime Earnings',
          'withdraw_earnings': 'Withdraw Earnings',
          'pending_amount': 'Pending Amount',
          'withdraw_amount': 'Withdraw Amount',
          'withdraw': 'Withdraw',
          'verify_to_withdraw': 'Verify To Withdraw',
          'explore_and_apply_job':
              'Explore and apply to the job category that interests you.',
          'eligible_job_category':
              'Start working on the jobs you are eligible for in that job category.',
          'approved_work': 'Get paid for all the approved work',
          'let_get_started': "Let ${"'"}s Get Started!",
          'explore_jobs_categories':
              'You can explore the job categories and get all details related to them.',
          'skip': 'Skip',
          'office_text':
              'You can view all the jobs available to you and jobs for which you need to complete application process here',
          'earning_text': 'You can track and withdraw your payments',
          'category_details': 'Here you can find the details of the category!',
          'my_jobs_details':
              'These are the jobs that you are ready to work or already working on!',
          'pending_jobs_details':
              'These are the jobs that are waiting for you to complete the onboarding.',
          'how_the_app_works': 'How The App Works',
          'how_the_app_works_description':
              'Please go through the ${'"'}How The App Works${'"'} section to see the demo videos',
          'see_demo_videos_work_better': 'See Demo Videos & work better',
          'demo_videos': 'Demo Videos',
          'heading_out_to_work': 'Heading out to work?',
          'worklog_question_description':
              'Fill out the questions below before starting your work each day',
          'demo_videos': 'Demo Videos',
          'verify_account': 'Verify Account',
          'get_verified': 'Get Verified',
          'verify_pan_and_bank_account':
              'Verify PAN and Bank Account to withdraw earnings',
          'pan_card': 'PAN Card',
          'verify': 'Verify',
          'bank_account': 'Bank Account',
          'note': 'Note : ',
          'make_sure_your_back_account_has_the':
              'Make sure your Bank account has the same name as your PAN card. If you face any issue please contact support.',
          'aadhar_card': 'Aadhar Card',
          'driving_license': 'Driving License',
          'loading_pan_card': 'Loading PAN Card...',
          'loading_aadhar_card': 'Loading Aadhar Card...',
          'loading_driving_license': 'Loading Driving License..',
          'verify_now': 'Verify Now',
          'confirm_your_pan_number_and_verify':
              'Confirm your PAN Number & Verify',
          'pan_number': 'PAN Number',
          'enter_pan_number': 'Enter PAN Number',
          'enter_pan_name': 'Enter PAN Name',
          're_upload': 'Re-upload',
          'select_account_to_verify': 'Select Account To Verify',
          'add_new_account': '+Add New Account',
          'add_bank_account': 'Add Bank Account',
          'add_upi_id': 'Add UPI ID',
          'account_number': 'Account Number',
          'enter_account_number': 'Enter Account Number',
          're_enter_account_number': 'Re-Enter Account Number',
          'ifsc_code': 'IFSC Code',
          'enter_ifsc_code': 'Enter IFSC Code',
          'enter_valid_account_number': 'Enter valid account number',
          'enter_valid_ifsc_code': 'Enter valid IFSC Code',
          'add_account': 'Add Account',
          'are_you_sure_want_to_submit': 'Are you sure want to submit?',
          'disabled_due_to_low_transfer_success_with_upi':
              'Disable due to low transfer success with UPI. Please proceed with Bank Account detail',
          'upi_id': 'UPI ID',
          'enter_upi_id': 'Enter UPI ID',
          'enter_valid_upi': 'Enter valid UPI ID',
          'disabled_due_to_maintenance': 'Disabled due to maintenance',
          'add_beneficiary': 'Add Beneficiary',
          'no_beneficiary_added': 'No Beneficiary Added',
          'add_beneficiary_to_receive_payment':
              'Add beneficiary to receive payment',
          'you_can_add_upto_5_accounts': 'You can add upto 5 accounts',
          'deactivate_account': 'Deactivate Account',
          'verification_failed': 'Verification Failed',
          'your_account_could_not_be_verified':
              'Your account could not be verified. Please try submitting the correct details again.',
          'okay': 'Okay',
          'maximum_account_reached': 'Maximum account reached',
          'maximum_5_accounts_have_been_reached':
              'Maximum 5 accounts have been reached. No further account can be added. Please ',
          'contact_customer_support': 'Contact Customer Support',
          'for_further_assistance': ' For further assistance.',
          'activate': 'Activate',
          'beneficiary_details': 'Beneficiary Details',
          'bank_name': 'Bank Name',
          'beneficiary_name': 'Beneficiary Name',
          'select_month_to_download_earning_statement':
              'Select month to download Earning Statement',
          'select_month': 'Select Month',
          'no_earnings': 'No Earnings',
          'you_have_not_earned_this_month': 'You have\'t earned this month',
          'minimum_amount_that_can_be_withdrawn':
              'Minimum amount that can be withdrawn',
          'tds': 'TDS',
          'tds_info_pan_ver_itr_t_one_lakh':
              '%1s\%%TDS deducted on Earning as your financial year earning is more than 1 Lakh. Click on \'i\' icon to know more about TDS deduction.',
          'tds_info_pan_ver_itr_f_one_lakh':
              '%1s\%%TDS deducted on Earning as your financial year earning is more than 1 Lakh. TDS will be deducted at %2s\%% if you have submitted ITR in the last two year. Please reach out to support if you have submitted the ITR. Click on \'i\' icon to know more about TDS deduction.',
          'tds_info_pan_ver_itr_t_thirty_k':
              '%1s\%%TDS deducted on Earning as withdrawal amount is more than 30,000. Click on \'i\' icon to know more about TDS deduction.',
          'tds_info_pan_ver_itr_f_thirty_k':
              '%1s\%%TDS deducted on Earning as withdrawal amount is more than 30,000. TDS will be deducted at %2s\%% if you have submitted ITR in the last two year. Please reach out to support if you have submitted the ITR. Click on \'i\' icon to know more about TDS deduction.',
          'final_amount': 'Final Amount',
          'select_beneficiary': 'Select Beneficiary',
          'make_sure_your_name_in_pan_card_and_bank_account_is_same':
              'Make sure your name in PAN Card and Bank account is same. If you face any issue please contact support.',
          'proceed_to_withdraw': 'Proceed To Withdraw',
          'withdrawal_request_initiated': 'Withdrawal request initiated',
          'withdrawl_initiated': 'Hurray! Your payment of',
          'it_usually_takes':
              ' is under process. It might take upto 5 hours for the payment to reflect in your bank account.',
          'ok': 'OK',
          'date': 'Date',
          'click_to_know_how': 'Click to know how',
          'tax_deduction': 'Tax Deduction',
          'details_not_found_please_check_after_sometime':
              'Details not found. Please check after sometime',
          'pan_card_not_verified': 'PAN card not verified',
          'pan_card_verified': 'PAN card verified',
          'upload_pan_card_to_withdraw_your_earnings':
              'Upload PAN card to withdraw your earnings',
          'in_progress': 'In Progress',
          'confirm_your_driving_license_details':
              'Confirm your Driving License Details',
          'make_sure_your_name_validity_dl_number':
              'Make sure your Name, Validity, DL Number and Date Of Birth is correct',
          'validity': 'Validity',
          'dl_validity': 'Driving License Validity',
          'driving_license_number': 'Driving License Number',
          'enter_driving_license_number': 'Enter Driving License Number',
          'please_enter_valid_validity': 'Please enter valid validity',
          'confirm_your_aadhar_number_and_verify':
              'Confirm your aadhar number and verify',
          'we_will_send_an_otp_to_the_number':
              'We will send an OTP to the number linked with the Aadhar',
          'aadhar_number': 'Aadhar number',
          'enter_aadhar_number': 'Enter Aadhar number',
          'verify_via_otp': 'Verify Via OTP',
          'not_submitted': 'Not Submitted',
          'campus_description':
              'As a Campus Ambassador, you will act as a bridge between Awign and the students from your college who are ambitious and are looking for opportunities to learn, earn and grow!\nThis is the right platform for you if you have good people skills and want to further improve them; if you aspire to be a leader in your domain, we will provide you the platform to get mentored by experts at Awign.',
          'apply_campus_ambassador':
              'Apply to the Campus Ambassador program by submitting your details (application from below)',
          'ambassador_task_description': 'Complete the task assigned to you',
          'ambassador_reward_desciption':
              'Get rewarded with a certificate of excellence, stipend and much more once you meet the targets',
          'why_ambassador_desciption':
              'Work remotely with Marketing experts from Awign, improve your network and nurture your interprsonal skills. You will become the bridge between Awign${"'"}s internships and student striving to learn & earn.',
          'grow_with_us':
              'We are creating thousands of opportunities for students pan India. We are growing and we want you to grow by helping students find the right internships/part-time jobs, and in turn, you get paid on achieving the numbers.',
          'be_that_guy':
              'Be the one who students as well as Awign can count on. You will be the one-point contact for all your friends and college mates looking for fantastic internship and career opportunities.',
          'earn_as_you_learn':
              'If you wish to, learning can go hand-in-hand with earning. Once you associate with us, we will ensure your holistic growth while adding incredible corporate experience to your resume.\nGet hands-on experience in online as well as offline marketing activities.',
          'reward':
              'Apart from massive stipend, certificate of excellence and a letter of recommendation,get a life-time privilege for guidance from the IIT${"'"}s &amp; IIM${"'"}s alumni. Not to mention,credit yourself as a campusambassador for Awign in your resume, LinkedIn profile, blogs, personal pages etc',
          'branding':
              'Creating brand awareness about Awign internships in your place, college and online community through social media, various social groups, and social gatherings.',
          'registration':
              'Get a large number of students to sign up on the Awign App via  provided link.',
          'social_media':
              'Extensively promote the assigned internship in your campus via social media platforms like Facebook, Twitter, WhatsApp, Instagram, etc).',
          'email_ambassador':
              'Circulate the internship mail to your student mailing list within 3 days of receiving the mailer.',
          'poster':
              'Put up the posters of the internship on the student notice board, college mess or canteen of your college within 4 days of receiving it.',
          'networking':
              'Help us connect with important stakeholders of your College (Example - College President, Cultural secretary , General secretary , Club heads, Head of major student groups of your campus).',
          'innovate':
              'Come up with ideas of collaboration between Awign &amp; your college. Lead the same from planning to implementation, post approval from your manager. Post successful execution, wait for the reward you couldn\'t have dreamt of.',
          'perk_description': 'The bright side of becoming a Campus Ambassador',
          'stipend_and_cetificate_desc':
              'Earn upto Rs 3,800 in 10 days and a certificate of excellence on achieving set targets',
          'full_time_paid_internship_desc':
              'Full-time paid internship with Awign (Head office, Bangalore) on exceptional performance',
          'merchandise_desc':
              'Exciting goodies, t-shirts & exclusive prizes for top 5 campus ambassadors',
          'credit_yourself_desc':
              'Credit yourself as a campus ambassador for Awign in your resume, LinkedIn profile, blogs, personal pages etc.',
          'disqualification': 'DISQUALIFICATIONS',
          '3_golden_roles': '3 golden roles -',
          '_3_golden_rules_don_t_lie_don_t_cheat_amp_don_t_give_up':
              '3 Golden Rules - don${"'"}t lie, don${"'"}t cheat & don${"'"}t give up.',
          'remember_you_will_be_disqualified_if':
              'Remember, you will be disqualified if:',
          'invalid_or_forceful_application': 'Invalid or forceful application',
          'any_application_is_found_to_be_fake_or_invalid_or_if_any_applicant_has_been_forced_to_apply_for_the_internship_which_is_clearly_out_of_their_interest':
              'Any application is found to be fake or invalid or if any applicant has been forced to apply for the internship which is clearly out of their interest.',
          'targets_not_met': 'Targets not met',
          'you_are_unable_to_reach_a_minimum_of_15_applications_in_first_3_days_of_commencement_of_your_duties':
              'You are unable to reach a minimum of 15 applications in first 3 days of commencement of your duties.',
          'forged_documents': 'Forged documents',
          'it_was_found_that_you_have_applied_on_someone_else_s_behalf':
              'It was found that you have applied on someone else\'s behalf.',
          'irrelevant': 'Irrelevant',
          'it_was_found_that_you_forced_or_convinced_someone_to_apply_for_internship_who_was_not_interested':
              'It was found that you forced or convinced someone to apply for internship who was not interested.',
          'disqualification_will_lead_to_cancellation_of_both_certificate_as_well_as_stipend':
              '*Disqualification will lead to cancellation of both certificate as well as stipend.',
          'apply_for_campus_ambassador': 'Apply for Campus Ambassador',
          'apply_now': 'Apply now',
          'apply': 'Apply',
          'parttime_desc':
              'Part-time internships all across India. Work few hours a day and earn handsome stipend. \nDownload Awign App Now!\n',
          'my_task': 'My Tasks',
          'application': 'Application',
          'no_application': 'No Application',
          'application_in_progress': 'Application In-Progress',
          'selected_applicants': 'Selected Applicants',
          'working_applicants': 'Working Applicants',
          'college': 'College',
          'application_sent': 'Application Sent',
          'okay': 'OKAY',
          'no_access': 'No Access',
          'you_dont_have_access_to_this_page':
              'You don${"'"}t have access to this page',
          'text_copied': 'Text copied',
          'notification_channel_title': 'Channel human readable title',
          'notification_title': 'Awign has a new message',
          'listing_unavailable': 'Listing Unavailable',
          'rate_us': 'Rate us',
          'rate_your_experience_with_us': 'Rate Your Experience With Us!',
          'your_feedback_helps_us_improve': 'Your feedback helps us improve',
          'please_share_your_experience_on_stuff_you_liked_or_disliked_optional':
              'Please share your experience on stuff you liked or disliked (Optional)',
          'please_add_suggestions': 'Please add suggestions',
          'thanks_for_sharing_your_feedback':
              'Thanks for sharing your feedback',
          'job_category': 'Job Category',
          'by_applying_you_will_be_eligible_for':
              'By applying you\'ll be eligible for this job & other jobs within the category',
          'provide_availability': 'Provide Availability',
          'availability_description':
              'Please provide your availability to work for Today & Tomorrow before proceeding to the project dashboard.',
          'select_time_slot': 'Select Time Slot',
          'please_provide_your_availability_for_today_so_that_we_can_allocate_tasks_accordingly':
              'Please provide your availability for Today so that we can allocate tasks accordingly.',
          'add_more_slot': '+ Add More Slot',
          'confirm_and_next': 'Confirm & Next',
          'i_am_not_available_to_work_today':
              'I am not available to work today',
          'not_available_today': 'Not available today',
          'provide_schedule_in_order_to_nwork_today':
              'Provide schedule in order to\nwork today',
          'today_schedule': 'Today${"'"}s Schedule',
          'please_provide_your_availability_for_tomorrow_so_that_we_can_allocate_tasks_accordingly':
              'Please provide your availability for Tomorrow so that we can allocate tasks accordingly.',
          'not_available': 'Not Available',
          'by_applying_you_will_be_eligible_for':
              'By applying you\'ll be eligible for this job & other jobs within the category',
          'work_start_date': 'Work start date',
          'revised_start_date': 'Revised start date',
          'active_users': 'Active Users',
          'potential_earning': 'Potential Earning',
          'we_regret_to_inform_you_that':
              'We regret to inform you that there is no work available. You’ll be notified once we have work for you.',
          'please_contact_support_to_get_your_aadhar_card_verified':
              'Please contact support to get your aadhar card verified.',
          'please_contact_support_to_get_your_pan_card_verified':
              'You have exceeded the maximum number of confirmations provided for PAN verification. Please reach out to support for verifying your PAN details',
          'you_ve_not_earned_anything_yet_start_working_to_earn':
              'You${"'"}ve not earned anything yet. Start working to earn.',
          'are_you_sure_you_want_to_change_screen':
              'Are you sure you want to change screens? Any unsaved data will be lost.',
          'change_screen': 'Change screen?',
          'delete_account': 'Delete Account',
          'are_you_sure_want_to_delete_your_account':
              'Are you sure want to delete your account?',
          'university': 'University',
          'filter_by_skills': 'Filter By Skills',
          'things_to_learn': 'Things to Learn',
          'start_learning': 'Start Learning',
          'no_course_found': 'No Course Found',
          'no_application_found': 'No Application Found',
          'do_not_disturb': 'Do Not Disturb',
          'unsubscribe_text': 'Unsubscribe from Calls, Text & Mail',
          'explore_similar_jobs': 'Explore similar jobs',
          'explore_job_categories': 'Explore job categories',
          'our_team_is_working_hard_to_find_work_for_you_you_will_be_notified_when_work_is_available':
              'Our team is working hard to find work for you. You will be notified when work is available.',
          'thanks_for_submitting_the_request_for_more_work_your_manager_has_been_informed':
              'Thanks for submitting the request for more work. Your manager has been informed',
          'start_working': 'Start Working',
          'request_for_work': 'Request for Work',
          'proceed_to_work': 'Proceed To Work',
          'similar_digital_gigs_jobs': 'Similar Digital Gigs Jobs',
          'request_submitted': 'Request submitted',
          'work_assigned': 'Work Assigned',
          'work_has_been_assigned_to_you_please_start_working':
              'Work has been assigned to you. Please start working.',
          'request_work': 'Request Work',
          'notification': 'Notification',
          'unread_notification': 'Unread notifications',
          'india_largst_gig_work_platform_Want_to_earn_and_grow_Youre_at_the_right_place':
              'India${"'"}s largest gig work platform. Want to earn and grow? You${"'"}re at the right place.',
          'login_or_signup': 'Login/Signup',
          'enter_10_digit_number': 'Enter 10 digit Number',
          'play_again': 'Play again',
          'login': 'Login',
          'login_to_awign': 'Login To Awign',
          'Largest_gig_work_platform_to_earn_grow':
              'Largest gig work platform to earn & grow.',
          'no_job_found': 'No jobs found',
          'Job_categories_you_apply_to_will_appear_here':
              'Job categories you apply to will appear here',
          'no_earnings_yet': 'No Earnings yet',
          'Start_working_and_keep_a_track_of_your_earnings_here':
              'Start working and keep a track of your earnings here',
          'work': 'WORK',
          'new_job': 'NEW JOBS',
          'no_notification': 'No Notification',
          'mark_as_all_read': 'Mark All As Read',
          'applied': 'Applied',
          'delete_this_account': 'Delete this Account',
          'reset_pin': 'Reset PIN',
          'login_singnup_with': 'Login / Signup with',
          'recommended_for_faster_login': 'Recommended for faster login',
          'login_via_whatsapp': 'Login via WhatsApp',
          'recieve_updates_on_whatsapp': 'Receive Updates on Whatsapp',
          'disable_whatsapp_notifications': 'Disable WhatsApp notifications?',
          'you_wont_recieve_notification':
              'You won${"'"}t receive any notifications or updated of Awign on your WhatsApp.',
          'disable': 'Disable',
          'by_enabling_this_feature_you_can_receive_all':
              'By enabling this feature, you can receive all notifications and updates on your WhatsApp.',
          'enable': 'Enable',
          'i_ll_do_it_later': 'I${"'"} ll do it later',
          'successfully_enabled': 'Successfully enabled!',
          'already_have_an_account': 'Already have an account?',
          'login_using_the_mobile_number':
              'Login using the mobile number of your existing account',
          'error_msg_for_same_mob_num':
              'Oops! You are already logged in with this mobile number. Please go back or enter a different mobile number.',
          'please_come_back_after': 'Please come back after',
          'you_can_start_joining_in_and_wait_for_trainer_to_come':
              'You can start joining in and wait for trainer to come',
          'your_webinar_has_started_please_join_the_meeting':
              'Your webinar has started. Please join the meeting by clicking below',
          'webinar_training': 'Webinar Training',
          'step_1': 'Step 1',
          'step_2': 'Step 2',
          'step_3': 'Step 3',
          'download_zoom_app': 'Download Zoom App',
          'copy_meeting_id': 'Copy meeting ID',
          'copied': 'Copied',
          'closed': 'Closed',
          'this_project_has_been_closed': 'This project has been closed.',
          'we_see_you_are_new_here': 'We see you’re new here!',
          'unlock_endless_opportunities_with_just_one_simple_step':
              'Unlock endless opportunities with just one simple step - enter your email to start your journey with us!',
          'enter_email_manually': 'Enter Email Manually',
          'create_account': 'Create Account',
          'create_account_with_the_phone_number':
              'Creating account with the phone number',
          'email_address': 'Email Address',
          'glad_to_have_you_with_us': 'Glad to have you with us,',
          'in_the_last_year_alone_we_have_helped':
              'In the last year alone, we have helped',
          'people_switch_from_regular':
              'people switch from regular 9-5 jobs, to a flexible gig work model that fits their needs and schedule.',
          'with_an_average_pay_of': 'With an average pay of',
          'per_month_people_have_improved':
              'people have improved their financial situation & gained valuable experience with us.',
          'tell_us_a_little_bit_about_your_preferences':
              'Tell us a little bit about your preferences to help us find relevant work for you',
          'fill_my_work_preferences': 'Fill my work preferences',
          'save_and_continue': 'Save and Continue',
          'dream_application': 'Dream Application',
          'let_us_know_your_professional_details_so_that_we_can_match':
              'Let us know your professional details so that we can match you with the perfect fit opportunities!',
          'complete_with_percent': '% Complete',
          'maybe_later': 'Maybe Later',
          'complete_now': 'Complete Now',
          'complete': 'Complete',
          'enter_full_name': 'Enter full name',
          'select_languages': 'Select languages',
          'account_already_exists': 'Account Already Exists',
          'account_linked_to': 'Account linked to',
          'to_use_the_existing_account_login_again_or_create_a_new_account':
              'To user the existing account login again or create a new account by using a different Email',
          'login_again_using': 'Login again using',
          'use_different_email_address': 'Use Different Email Address',
          'thanks_for_submitting': 'Thanks for submitting!',
          'if_you_want_to_complete_your_profile':
              'If you want to complete your profile, head over to the Profile tab.',
          'add': 'Add',
          'added': 'Added',
          'whats_app_notification': 'Whats App Notification',
          'profile_attributed_updated': 'Profile attributed updated',
          'select_your_passing_year': 'Select your passing year',
          'leaderboard': 'Leaderboard',
          'top_earner': 'Top 5 Earners',
          'your_performance': 'Your Performance',
          'your_earnings': 'Your earnings',
          'view_goals': 'View Goals',
          'tips_to_improve': 'Tips To Improve',
          'you_are_capable_of_even_more_learn_the_secrets':
              'You${"'"}re capable of even more! Learn the secrets from the tips & insights.',
          'how_to_earn_more': 'How to earn \nmore ?',
          'increase_your_performance_score': 'Increase your performance score',
          'request_more_task_from_your_manager':
              'Request more task from your manager',
          'complete_your_task_in_stipulated_time':
              'Complete your tasks in stipulated time to get more work.More Work = More Pay',
          'work_on_parallel_job':
              'Work on parallel job, multitasking is the Gig way',
          'certificate_awarded': 'Certificate Awarded',
          'keep_up_the_good_work': 'Keep up the good work!',
          'you_can_view_share':
              'You can view & share your certificate on the last day of the month',
          'my_goals': 'My Goals',
          'track_your_progress':
              'Track your progress here and keep working to achieve your goals!',
          'good': 'Good',
          'earn_good': 'Earn ₹15,000 more to reach here & get a certificate',
          'earn_average': 'Earn ₹15,000 more to reach here',
          'earn_excellent':
              'Earn ₹15,000 more to reach here & get a certificate',
          'average': 'Average',
          'excellent': 'Excellent',
          'share_certificate': 'Share Certificate',
          'congratulations': 'Congratulations!',
          'congratulation_first_part': 'You have been awarded a ',
          'congratulation_second_part': ' Certificate of Appreciation',
          'congratulation_third_part': ' for performing Good in the month of ',
          'congratulation_fourth_part': ' Certificate of Merit',
          'congratulation_fifth_part': ' for finishing at ',
          'congratulation_sixth_part': ' place among all the users',
          'poor': 'Poor',
          'average_work_desc':
              'Your work is encouraging, but are capable of even more. Learn the secrets from the tips & insights.',
          'your_Earnings': 'Your Earnings',
          'rank_one_desc': 'Congratulation on finishing at ',
          'rank_two_desc': ' place among all the users',
          'congratulation_second_desc':
              'You Should be proud of your accomplishment and the hard work and dedication that you put in to earn this recognition. Share this with your friends and family.',
          'top_onboarding_user': 'Top 5 Job-onboarding users',
          'your_job': 'Your Jobs',
          'job_onboarding_improve_desc':
              'We appericiate your effort but want you to excel. Check the tips & insight now.',
          'how to get more task':
              'How to get more tasks \n& increase your work?',
          'improve_your_job_onboarding':
              'How to improve your\n job onboardings?',
          'attend_all_webinar': 'Attend all Webinar and trainings',
          'go_through_all_the_material':
              'Go through all the material shared by Awign team during your onboarding process',
          'apply_for_similar_jobs':
              'Apply for similar jobs to increase your chances of selection',
          'top_most_task': 'Top 5 users with most tasks',
          'your_tasks': 'Your Tasks',
          'your_effort_show_promise':
              'Your effort show promise and you can do better! Check the tips & insight now.',
          'want_to_climb_the_ladder':
              'Want to climb the ladder and stand out amongst other colleagues? Check exclusive insights & Tips',
          'request_more_task': 'Request more tasks from your manager',
          'increase_your_quality': 'Increase your quality score for each task',
          'come_back_later': 'Come back later!',
          'leaderboard_will_start':
              'Leaderboard will start from 5th \nof this month',
          'not_yet_started': 'Not yet started',
          'explore_categories': 'Explore categories, job and \nbegin work',
          'rank_three_desc': ' place in top earner list',
          'awesome': 'Awesome',
          'poor_performance': 'Poor Performance',
          'average_performance': 'Average Performance',
          'good_performance': 'Good Performance',
          'excellent_performance': 'Excellent Performance',
          'app_version': 'App Version',
          'thanks_for_chossing_awign':
              'Thanks for choosing Awign. \n We${"'"}re connecting you to your next gig opportunity.',
          'introducing': 'INTRODUCING',
          'dream': 'Dream',
          'my_application': 'My Application',
          'be_the_first_to_reached_out':
              'Be the first to be reached out for projects with personalised one-on-one assistance! Your profile will be matched to keep you ahead of the game.',
          'thanks_for_chossing_awign':
              'Thanks for choosing Awign. \n We${"'"}re connecting you to your next gig opportunity.',
          'poor_performance': 'Poor Performance',
          'average_performance': 'Average Performance',
          'good_performance': 'Good Performance',
          'excellent_performance': 'Excellent Performance',
          'app_version': 'App Version',
          'duplicate': 'Duplicate',
          'thanks_for_chossing_awign':
              'Thanks for choosing Awign. \n We${"'"}re connecting you to your next gig opportunity.',
          'call': 'Call',
          'call_bridge': 'Call bridge',
          'more_action': 'More action',
          'more_action_': 'More Action:',
          'action_not_set': 'action not set',
          'connect_call': 'Connect Call',
          'verify_phone_number': 'Verify Phone number',
          'please_make_sure_the_number_you_have_entered_is_correct_you_will_get_a_call_on_the_entered_number':
              'Please make sure the number you have entered is correct. You will get a call on the entered number.',
          'whatsapp_not_found': 'WhatsApp not found',
          'location_not_found': 'Location not found',
          'phone_not_found': 'Phone not found',
          'email_not_found': 'Email not found',
          'connect_call': 'Connect Call',
          'verify_phone_number': 'Verify Phone number',
          'please_make_sure_the_number_you_have_entered_is_correct_you_will_get_a_call_on_the_entered_number':
              'Please make sure the number you have entered is correct. You will get a call on the entered number.',
          'whatsapp_not_found': 'WhatsApp not found',
          'location_not_found': 'Location not found',
          'phone_not_found': 'Phone not found',
          'email_not_found': 'Email not found',
          'connect_call': 'Connect Call',
          'verify_phone_number': 'Verify Phone number',
          'please_make_sure_the_number_you_have_entered_is_correct_you_will_get_a_call_on_the_entered_number':
              'Please make sure the number you have entered is correct. You will get a call on the entered number.',
          'whatsapp_not_found': 'WhatsApp not found',
          'location_not_found': 'Location not found',
          'phone_not_found': 'Phone not found',
          'email_not_found': 'Email not found',
          'connect_call': 'Connect Call',
          'verify_phone_number': 'Verify Phone number',
          'please_make_sure_the_number_you_have_entered_is_correct_you_will_get_a_call_on_the_entered_number':
              'Please make sure the number you have entered is correct. You will get a call on the entered number.',
          'whatsapp_not_found': 'WhatsApp not found',
          'location_not_found': 'Location not found',
          'phone_not_found': 'Phone not found',
          'email_not_found': 'Email not found',
          'duplicate_lead': 'Duplicate Lead',
          'close_screen': 'Close Screens',
          'any_unsaved_data':
              'Are you sure you want to close screens? Any unsaved data will be lost permanently',
          'connect_call': 'Connect Call',
          'verify_phone_number': 'Verify Phone number',
          'please_make_sure_the_number_you_have_entered_is_correct_you_will_get_a_call_on_the_entered_number':
              'Please make sure the number you have entered is correct. You will get a call on the entered number.',
          'whatsapp_not_found': 'WhatsApp not found',
          'location_not_found': 'Location not found',
          'phone_not_found': 'Phone not found',
          'email_not_found': 'Email not found',
          'your_approved_earnings': 'Your Approved Earnings',
          'early_withdrawal_charges_applicable':
              '*Early withdrawal charges applicable',
          'get_additional_earning':
              'Get additional earnings \nbefore their due date!',
          'deductions_applicable': '*Deductions applicable',
          'why_wait_to_withdraw': 'Why wait to Withdraw ?',
          'why_wait_to_withdraw_desc':
              'Hi fellow workers, you can now take out your upcoming earnings before time! Upcoming earnings are your approved earnings which are not yet matured.',
          'withdrawable_earnings': 'Withdrawable Earnings',
          'upcoming_earnings': 'Upcoming Earnings',
          'total_withdraw': 'Total Withdraw',
          'proceed': 'Proceed',
          'view_all_charges': 'View all charges',
          'earnings_overview': 'Earnings Overview',
          'what_are_upcoming_earnings': 'What are Upcoming Earnings?',
          'what_are_upcoming_earnings_desc':
              'Upcoming earnings are your approved earnings which are not yet matured. Open the gateway to abundance right now!',
          'what_are_deductions': 'What are these deductions?',
          'what_are_deductions_desc':
              'When it comes to deductions, there are two categories:',
          'early_withdrawal_charges': 'Early Withdrawal Charges',
          'deductions': 'Deductions',
          'hide_charges': 'Hide charges',
          'confirm_amount': 'Confirm Amount',
          'overall_deduction': 'Overall deductions',
          'total': 'Total',
          'charges_depend_on_desc':
              'Charges depends on the difference between withdraw and approval date of the individual upcoming amount. These charges are non-refundable.',
          'terms_and_condition_applied': 'Terms & Conditions Applied',
          'find_more_work': 'Find More Work!',
          'approval_date': 'Approval \n    date',
          'upcoming_account': 'Upcoming \namount',
          'charges_on': 'charges on\n  approval date',
          'total_deduction': 'Total Deduction',
          'complete_kyc': 'Complete Kyc',
          'your_upcoming_earning_zero': 'Your Upcoming earning is 0',
          'your_withdrawl_earning_zero': 'Your Withdrawl earning is 0',
          'early_withdrawl_charge': 'Early Withdrawal Charge',
          'deduction_categories_one':
              'Early Redemption Policy: Use a small amount to access your upcoming earnings ahead of time, even before they fully mature.',
          'show_all_deduction': 'Show all deductions',
          'deduction_categories_two':
              'TDS (Tax Deducted at Source): Awign deducts specific taxes from your income and deposit them directly to the government on your behalf, ensuring prompt tax payment.',
          'know_more': 'Know More',
          'early_redemption_policy': 'Early Redemption Policy',
          'please_not_the_following_points':
              'Please note the following points:',
          'value_payout_desc':
              'The value of the payout on the due date will be considered 100%. Apart from that if the withdrawal happens before the due date, the payout will be reduced by case by case per day.',
          'example_redemption_desc':
              'For example, the deduction plan would be as mentioned:',
          'values_amount_desc':
              '**all values and amounts are tentative and may vary on a case by case basis. Current deduction % considered is 0.15% per day.',
          'refundable_desc':
              'The early withdrawal deduction is non-refundable.',
          'view_all_dedc': 'View all deductions',
          'all_deduction': 'All Deductions',
          'early_redemption_deduction': 'Early redemption deduction',
          'currently_unavailable': 'Currently Unavailable',
          'currently_unavailable_desc':
              'Our ${"‘"}upcoming earnings${"’"} feature is still on its way, ready to unlock new possibilities for you. Stay tuned for more updates!',
          'i_approve_deduction': 'I approve deductions on earnings',
          'download_file_text': 'You have to Download File to attend Training',
          'prepare_for_training': 'Prepare For Training',
          'copy_meeting_password': 'Copy Meeting Password',
          'ineligible': 'Ineligible',
          'dont_full_eligibility_text':
              'You don’t fulfill the required eligibility criteria for this project.',
          'check_eligibility': 'Check Eligibility',
          'eligibility_criteria': 'Eligibility Criteria',
          'update_my_application': 'Update My Application',
          'update_application_text':
              'Update application if you fulfill the eligibility criteria',
          'update_application': 'Update Application',
          'changing_response_might_affect_eligibility_for_other_jobs':
              'Changing response might affect eligibility for other jobs',
          'updating_your_application':
              'Updating your application responses may have an impact on other job application. Do you want to continue ?',
          'poor_performance': 'Poor Performance',
          'average_performance': 'Average Performance',
          'good_performance': 'Good Performance',
          'excellent_performance': 'Excellent Performance',
          'basic_req': 'Basic Requirements',
          'earn_upto': 'Earn upto',
          'proceed_next_step': 'Proceed to next step',
          'available_job': 'Available Job',
          'salary_detail': 'Salary details',
          'view_jobs_desc': 'View job description',
          'login_to_apply': 'Login To Apply',
          'notify_me_text':
              'Click on notify me and we\'ll notify you when new opportunities are available',
          'notify_me': 'Notify Me',
          'notified_text': 'You will be notified once jobs become available',
          'you_will_be_notified_soon': 'You will be notified soon!',
          'notify_when_jobs_available':
              'We will notify you as soon as new job opportunities become available in this category.',
          'sit_back_and_relax':
              'Sit back and relax - We\'ll notify you of any new job opportunities in this category as soon as they become available.',
          'stay_updated': 'Stay Updated !',
          'click_on_notify_me_and_stay_updated_for_new_opportunities':
              'Click on Notify Me and stay updated for new opportunities',
          'sync_again': 'Sync Again',
          'data_not_found': 'data_not_found',
          'view_images': 'View Images',
          'uploaded': 'Uploaded',
          'of': 'Of',
          'add_more_images': 'Add more images',
          'do_not_move_please_wait': 'Don\'t move, please wait...',
          'please_enable_your_location_in_order_to_work':
              'Please enable your location in order to work',
          'enable_location': 'Enable Location',
          'map_view': 'Map View',
          'lead_not_found': 'Lead(s) not found',
          'payment_unsuccessful': 'Payment Unsuccessful',
          'payment_is_under_process': 'Payment is under process',
          'payment_under_process': 'Payment under process',
          'initiate_withdrawal': 'Initiate Withdrawal',
          'no_upcoming_earnings_found': 'No Upcoming Earnings Found',
          'withdrawal_confirmation': 'Withdrawal Confirmation',
          'cannot_proceed_due_to_less_balance':
              '*Cannot proceed to withdraw as total amount less than 100',
          'yay_your_payment_is_under_process':
              'Yay! Your payment is under process!',
          'great': 'Great!',
          'no_resource': 'No Resource',
          'go_back': 'Go Back',
          'something_went_wrong': 'Something went wrong!',
          'cannot_proceed_to_withdraw_as_total_amount_less_than_100':
              '*Cannot proceed to withdraw as total amount less than 100.',
          'payments_after_3_pm_will_be_processed_next_day_at_8_pm':
              'Payments after 3 PM will be processed next day at 8 PM',
          'please_add_valid_driving_license_number':
              'Please add valid driving license number',
          'mark_attendance': 'Mark Attendance',
          'bgv_address_verification': 'BGV Address Verification',
          'time_limit': 'Time Limit:',
          'attendance_marked': 'Attendance marked',
          'successfully': 'successfully',
          'start_work': 'Start Work',
          'you_have_missed_to_punch_in_today':
              'You have missed to Punch-In today',
          'contact_your_manager': 'For any changes, contact \nyour manager.',
          'kindly_mark_your_attendance':
              'Kindly mark your attendance \nbefore start working.',
          'punch_in': 'Punch-In',
          'do_it_later': 'Do it Later',
          'total_work_hour': 'Total work hours:',
          'punch_out': 'Punch-Out',
          'you_have_missed_to_punch_out_today':
              'You have missed to Punch-Out today',
          'please_enable_your_location': 'Please enable your \nGeo location',
          'please_allow_us_to_capture':
              'Please allow us to capture your \nGeo location to mark your attendance',
          'open_settings': 'Open settings',
          'location_captured': 'Location Captured',
          'please_enable_your_camera': 'Please enable your \ncamera',
          'please_allow_us_to_access_your_camera':
              'Please allow us to access \nyour camera  to mark attendance',
          'take_a_selfie': 'Take a selfie',
          'upload_image': 'Upload Image',
          'please_enable_access_to_your_files':
              'Please enable access to your files',
          'please_access_photos':
              'Please allow us to access photos, media and files, to mark your attendance',
          'input_fields': 'Input fields',
          'answer_the_following': 'Answer the following',
          'payment_unsuccessful': 'Payment Unsuccessful',
          'payment_is_under_process': 'Payment is under process',
          'payment_under_process': 'Payment under process',
          'initiate_withdrawal': 'Initiate Withdrawal',
          'no_upcoming_earnings_found': 'No Upcoming Earnings Found',
          'withdrawal_confirmation': 'Withdrawal Confirmation',
          'cannot_proceed_due_to_less_balance':
              '*Cannot proceed to withdraw as total amount less than 100',
          'yay_your_payment_is_under_process':
              'Yay! Your payment is under process!',
          'great': 'Great!',
          'go_back': 'Go Back',
          'something_went_wrong': 'Something went wrong!',
          'cannot_proceed_to_withdraw_as_total_amount_less_than_100':
              '*Cannot proceed to withdraw as total amount less than 100.',
          'payments_after_3_pm_will_be_processed_next_day_at_8_pm':
              'Payments after 3 PM will be processed next day at 8 PM',
          'map_view': 'Map View',
          'lead_not_found': 'Lead(s) not found',
          'submit_proceed': 'Submit & Proceed',
          'take_selfie_for_attendance': 'Take a selfie for attendance',
          'app_update': 'App update?',
          'please_update_to_continue_using_the_app':
              'Please update to continue using the app',
          'later': 'Later',
          'update': 'Update',
          'cannot_proceed_to_withdraw_as_total_amount_less_than_100':
              '*Cannot proceed to withdraw as total amount less than 100.',
          'payments_after_3_pm_will_be_processed_next_day_at_8_pm':
              'Payments after 3 PM will be processed next day at 8 PM',
          'add_signature': 'Add Signature',
          'please_sign_first': 'Please Sign First',
          'verify_pan': 'Verify PAN',
          'please_provide_details_of_your_pan':
              'Please provide details of your PAN ',
          'enter_your_pan_or_upload': 'Enter your PAN or upload',
          'to_auto_capture_pan_click_on_camera_icon':
              'To auto capture PAN, click on camera icon',
          'for_successful_verification_the_name_on_your_bank_account':
              'For successful verification, the name on your bank account and PAN card must be the same.',
          'to_ensure_the_accuracy_of_your_pan_card_details':
              'To ensure the accuracy of your PAN Card details, we will verify it through the Government portal.',
          'confirm_pan': 'Confirm PAN',
          'i_confirm_i_am': 'I confirm, I am ',
          'wrong_name_try_again': 'Wrong name? Try again',
          'take_a_photo': 'Take a Photo',
          'loading_pan_card': 'Loading PAN card...',
          'please_match_pan_with_the_below_image':
              'Please match PAN with the below image',
          'hello': 'Hello',
          'your_current_name': 'Your current name',
          'in_your_profile_section_will_get_updated_to':
              'in your Profile section will get updated to',
          'please_confirm_if_we_have_identified_the_correct_name':
              'Please confirm if we have identified the correct name.',
          'pan_does_not_exist': 'PAN does not exist',
          'too_many_attempts': 'Too Many Attempts',
          'pan_already_exist': 'PAN already exist',
          'verified': 'Verified',
          'pan_verified_successfully': 'PAN verified successfully.',
          'verify_to_withdraw_with_arrow': 'Verify to Withdraw ->',
          'pan_card_details': 'PAN Card Details',
          'pan_name': 'PAN Name',
          'verify_pan': 'Verify PAN',
          'please_provide_details_of_your_pan':
              'Please provide details of your PAN ',
          'enter_your_pan_or_upload': 'Enter your PAN or upload',
          'to_auto_capture_pan_click_on_camera_icon':
              'To auto capture PAN, click on camera icon',
          'for_successful_verification_the_name_on_your_bank_account':
              'For successful verification, the name on your bank account and PAN card must be the same.',
          'to_ensure_the_accuracy_of_your_pan_card_details':
              'To ensure the accuracy of your PAN Card details, we will verify it through the Government portal.',
          'confirm_pan': 'Confirm PAN',
          'i_confirm_i_am': 'I confirm, I am ',
          'wrong_name_try_again': 'Wrong name? Try again',
          'take_a_photo': 'Take a Photo',
          'loading_pan_card': 'Loading PAN card...',
          'please_match_pan_with_the_below_image':
              'Please match PAN with the below image',
          'hello': 'Hello',
          'your_current_name': 'Your current name',
          'in_your_profile_section_will_get_updated_to':
              'in your Profile section will get updated to',
          'please_confirm_if_we_have_identified_the_correct_name':
              'Please confirm if we have identified the correct name.',
          'pan_does_not_exist': 'PAN does not exist',
          'too_many_attempts': 'Too Many Attempts',
          'pan_already_exist': 'PAN already exist',
          'verified': 'Verified',
          'pan_verified_successfully': 'PAN verified successfully.',
          'verify_to_withdraw_with_arrow': 'Verify to Withdraw ->',
          'pan_card_details': 'PAN Card Details',
          'pan_name': 'PAN Name',
          'cannot_proceed_to_withdraw_as_total_amount_less_than_100':
              '*Cannot proceed to withdraw as total amount less than 100.',
          'payments_after_3_pm_will_be_processed_next_day_at_8_pm':
              'Payments after 3 PM will be processed next day at 8 PM',
          'hey_serkan': 'Hey, ',
          'enter_text_or_open_scanner': 'Enter Text or open ',
          'your_review_is_valuable_to_us': 'Your review is valuable to us.',
          'do_you_want_to_continue_scanning':
              'Do you want to continue scanning ?',
          'if_not_please_enter_details_manually':
              'If not, please enter details manually',
          'share_your_experience':
              'Share your experience to empower Awign in delivering an exceptional experience tailored just for you.😇',
          'how_likely_are_you_to_recommend_awign':
              'How likely are you to recommend Awign to a friend or colleague?',
          'not_likely': '0 - >Not Likely | 10 - >Extremely Likely',
          'alert': 'Alert',
          'you_have_only_x_attempts_left_to_verify_the_pan': 'You have only %1s attempts left to verify the PAN',
          'enter_valid_input': 'Enter valid input',
          'please_align_the_barcode_within_the_scanner':
              'please align the barcode within the scanner',
          'character_limit_exceeded': 'Character Limit Exceeded',
          'unable_to_recognise_a_valid_code_from_the_uploaded_image' : 'Unable to recognise a valid code from the uploaded image',
        },
        'hi': {
          'app_name': '',
          'server_error':
              'हमें तकनीकी त्रुटि के लिए खेद है। कृपया कुछ समय बाद पुन: प्रयास करें।',
          '': '',
        },
      };
}
