class AwignPermissionConstants {
  static const String applications = "applications";
  static const String earnings = "earnings";
  static const String campusAmbassador = "campus_ambassador";
  static const String referral = "referral";
  static const String jobs = "jobs";
  static const String listView = "list_view";
  static const String listings = "listings";
  static const String hideCampusAmbassador = "hide_campus_ambassador";
  static const String hideEarningsSection = "hide_earnings_section";
  static const String hideLeadListView = "hide_lead_list_view";
  static const String hideUniversitySection = "hide_university_section";
  static const String hideCompleteProfile = "hide_complete_profile";
  static const String hideOfferLetter = "hide_offer_letter";
  static const String hideApplicationHistory = "hide_application_history";
  static const String hideIdProof = "hide_id_proof";
  static const String hideDoNotDisturb = "hide_do_not_disturb";
  static const String hideHowTheAppWorks = "hide_how_the_app_works";
  static const String hideExploreSection = "hide_explore_section";
  static const String hideResetPIN = "hide_reset_pin";
  // static const String hidePendingApplications = "hide_pending_applications"; // Current Tdo Also in Android
  static const String hideApplicationDetails = "hide_application_details";
  static const String hidePendingJobs = "hide_pending_jobs";
  static const String hideActiveUsers = "hide_active_users";
  static const String hidePotentialEarning = "hide_potential_earning";
  static const String hideTotalEarnings = "hide_total_earnings";
  static const String hideCertificate = "hide_certificate";
  static const String hideGuidedTour = "hide_guided_tour";
}
